env:
  global:
  - GIT_NAME: "'Markdown autodeploy'"
  - GIT_EMAIL: djw8605@gmail.com
  - GH_REF: git@github.com:opensciencegrid/gracc.git
language: python
before_script:
- pip install mkdocs
- pip install MarkdownHighlight
- pip install mkdocs-material
script:
- mkdocs build
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -K $encrypted_deeca9072356_key -iv $encrypted_deeca9072356_iv -in deploy-key.enc -out deploy-key -d; chmod 600 deploy-key; eval `ssh-agent -s`; ssh-add deploy-key; fi
- git config user.name "Automatic Publish"
- git config user.email "djw8605@gmail.com"
- git remote add gh-token "${GH_REF}";
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then git fetch gh-token && git fetch gh-token gh-pages:gh-pages; fi;
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then PYTHONPATH=src/ mkdocs gh-deploy -v --clean --remote-name gh-token; fi;
notifications:
  slack:
    secure: ACF89H0k/tL2ztrgt/PyUJ1nFypTmobye+5sLPzqAjQbLtW+XDaMaMJY8n8/6RRcHAAnqFsV1I5I8cp3TaY7OttGsMzaXcSaqhOIfO8VBMX0vGwW5M2CJfcoy9sApabddn7kLNSthknPiHQu/yKM3q9XpIs8XSbXZEK9mxOY+2YIQvuYIDziJsne2lhCWuA6cSkI155q1RPYWaZXMQ+4mJwoBVKfk1TesAJB0HtJ5E+G798vs+TKMOFT2LCIHCScPZ/raw11LTC4FHaxjgWcA3A3pDA3HRszgIMH3SjQF76y+mLrQ7rIaocIR0ElG9BDK/g7czfhYG88ffhT53mEchrCEqcQ7RSpdZAM/1ibxieJEOZZ1ylTicV+GOeYCKIMmISvEltqk4A3tTxq1R/zC+KZMzVZyp93AAQwai60BuA1A00qTrXEJpro2kp/XluE0bFK4Mqf3Rznt3KXY+7GDRZY7g85Tu+kh8Pv5LFmkfwNhu4c7vkCfzUal+cbU91cOKWgMPHxk00Kz6A49kkSUsLA1kxmBaqQuCrtoTVDcIwobG565l+fyTTozCpJ0j+kRELaf6a7u5qexwqaUmjKEP+Hn7eZ8u82lUlbXE7uD9BALHj8c9hv80YgcLrQtKVwDZ4GwYrTb7MbFjlWBfmW4sdFXE8e+5gE6wBwD9Ba22w=
