site_name: GRACC Documentation
repo_url: https://github.com/opensciencegrid/gracc
copyright: Open Science Grid

theme: readthedocs

pages:
  - 'Introduction': 'index.md'
  - Development Docs:
    - Agent Architecture: dev-docs/agent-arch.md
    - Message Queues: dev-docs/message-queues.md
  - Operator Docs:
    - GRACE Installation: dev-docs/install-grace-db.md

extra_css: 
  - css/extra.css

markdown_extensions:
  - admonition

